version: 2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.0
    steps:
      - checkout
      - run: mvn verify

workflows:
  version: 2
  orbs:
    heroku: circleci/heroku@0.0.10
  build-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build