version: 2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.0
    steps:
      - checkout
      - run: mvn verify
  deploy:
    steps:
      - checkout
      - run:
          command: git push https://heroku$HEROKU_API_KEY@git.heroku.com/pw-football.git master

workflows:
  version: 2.0
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            build